name: Lint

on:
  push:
    branches:
      - release
  pull_request:

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: build
        run: yarn build

      # needed to generate abi
      - name: Build solidity
        run: forge build

      # - name: Lint
      #   run: yarn prettier

      - name: Deploy to dist branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }} # 默认token有推送权限，但仅限于当前repo
          publish_dir: ./dist
          publish_branch: dist # 部署到的分支
          commit_message: 'Automatically deploy from main' # 提交消息

      - name: Create Release Tag
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a v${{ github.sha }} -m "Automated release from commit ${{ github.sha }}"
          git push origin v${{ github.sha }}